[package]
name = "rust_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_backend"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.2", features = ["extension-module"] }
sha2 = { version = "0.10.8", default-features = false } # Cryptography utility